//
//  DetailsConfig.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailsConfig: BaseConfig{
    func createModule(view: DetailsViewController,repo:Repos) {
        
        let interactor: DetailsInteractor = DetailsInteractor(repo: repo)
        let router: DetailsRouter = DetailsRouter()
        
        let presenter: DetailsPresenter = DetailsPresenter(view: view, interactor: interactor, router: router)
        router.view = view
        interactor.basePresenter = handleBasePresenter(baseView: view)
        view.presenter = presenter
        interactor.presenter = presenter
        presenter.baseView = view
    }
}
