//
//  DetailsInteractor.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailsInteractor: BaseInteractor<AppTarget>,DetailsInteractorInputProtocol {

    weak var presenter: DetailsInteractorOutputProtocol?
    
    private var repo:Repos
    
    init(repo:Repos) {
        self.repo = repo
        super.init()
    }
    func fetchDetails() {
        presenter?.didLoadRepo(repo: repo)
    }
    func repoUrl() -> String {
        return repo.url ?? ""
    }
}
