//
//  DetailsRouter.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailsRouter: DetailsRouterProtocol {
    
    var view: UIViewController!
    
    func openInGithub(url: String) {
        guard let url = URL(string: url) else { return }
        UIApplication.shared.open(url)
    }
    
    
}
