//
//  DetailsProtocols.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol DetailsViewProtocol: class {
    var presenter: DetailsPresenterProtocol?  { get set }
    var labelTitle: UILabel!  { get set }
    var labelCreateAt: UILabel!  { get set }
    var labelRate: UILabel!  { get set }
    var labelFork: UILabel!  { get set }
    var labelLanguage: UILabel!  { get set }
    func loadTitle(str:String)
}
//MARK: Presenter -
protocol DetailsPresenterProtocol: class {
    var view: DetailsViewProtocol?  { get set }
    func loadLayout()
    func openInGithub ()
}

//MARK: Interactor -
protocol DetailsInteractorOutputProtocol: class {
    func didLoadRepo(repo:Repos)
    
}
protocol DetailsInteractorInputProtocol: class {
    
    var presenter: DetailsInteractorOutputProtocol?  { get set }
    func fetchDetails()
    func repoUrl() -> String
}

//MARK: Router -
protocol DetailsRouterProtocol: class {
    var view: UIViewController! { get set }
    func openInGithub(url:String)
}
