//
//  DetailsViewController.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailsViewController: BaseViewController, DetailsViewProtocol {

	var presenter: DetailsPresenterProtocol?

    @IBOutlet weak var githubBtn: UIButton!
    @IBOutlet weak var labelTitle: UILabel!
    @IBOutlet weak var labelCreateAt: UILabel!
    @IBOutlet weak var labelRate: UILabel!
    @IBOutlet weak var labelFork: UILabel!
    @IBOutlet weak var labelLanguage: UILabel!
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController!.navigationBar.prefersLargeTitles = true
        githubBtn.layer.cornerRadius = 8
        presenter?.loadLayout()
        
    }
    func loadTitle(str: String) {
        self.title = str
    }

    @IBAction func github(_ sender: Any) {
        presenter?.openInGithub()
    }
    
}
