//
//  RepoViewController.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Network

class RepoViewController: BaseViewController, RepoViewProtocol {
    
    @IBOutlet weak var noInternetImageVIew: UIImageView!
    @IBOutlet weak var seg: UISegmentedControl!
    @IBOutlet weak var repoCollectionView: UICollectionView!
    
    var presenter: RepoPresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        Reachability().checkForInternet(action: { (value) in
            DispatchQueue.main.async {
                if value {
                    self.repoCollectionView.isHidden = false
                    self.seg.isHidden = false
                    self.noInternetImageVIew.isHidden = true
                    self.setSegment()
                    self.presenter?.presenterViewDidLoad()
                    self.presenter?.loadRepos(timeframe: .Day)
                } else {
                    self.noInternetImageVIew.isHidden = false
                    self.repoCollectionView.isHidden = true
                    self.seg.isHidden = true
                }
            }
        })
        
    }
    func setSegment() {
        seg.selectedSegmentTintColor = Palette.slateGrey
        seg.tintColor = Palette.slateGrey
        seg.ensureiOS12Style()
    }
    
    @IBAction func onSegmentChanged(_ sender: UISegmentedControl) {
        switch sender.selectedSegmentIndex {
        case 0:
            self.presenter?.loadRepos(timeframe: .Day)
            break
        case 1:
            self.presenter?.loadRepos(timeframe: .Week)
            break
        case 2:
            self.presenter?.loadRepos(timeframe: .Month)
            break
        default:
            break
        }
    }
    
}
