//
//  RepoConfig.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RepoConfig: BaseConfig{
    func createModule(view: RepoViewController) {
        
        let interactor: RepoInteractor = RepoInteractor()
        let router: RepoRouter = RepoRouter()
        
        let presenter: RepoPresenter = RepoPresenter(view: view, interactor: interactor, router: router)
        
        router.view = view
        interactor.basePresenter = handleBasePresenter(baseView: view)
        view.presenter = presenter
        
        interactor.presenter = presenter
        presenter.baseView = view
    }
}
