//
//  RepoViewController.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import BetterSegmentedControl

class RepoViewController: BaseViewController, RepoViewProtocol {
    
    @IBOutlet weak var repoTableView: UITableView!
    @IBOutlet weak var controlFrameView: UIView!
    var presenter: RepoPresenterProtocol?
    var control:BetterSegmentedControl!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        addSegmentControll()
        self.presenter?.loadRepos()
    }
    
    func addSegmentControll () {
        self.control = BetterSegmentedControl(
            frame: controlFrameView.frame,
            segments: LabelSegment.segments(withTitles: ["Day", "Week", "Month"],
                                            normalFont: UIFont(name: "HelveticaNeue-Light", size: 14.0)!,
                                            normalTextColor: Palette.slateGrey,
                                            selectedFont: UIFont(name: "HelveticaNeue-Bold", size: 14.0)!,
                                            selectedTextColor: .white),
            index: 1 ,
            options: [.backgroundColor(.clear),
                      .indicatorViewBackgroundColor(Palette.slateGrey) , .cornerRadius(4),.indicatorViewBorderWidth(1),.indicatorViewBorderColor(Palette.slateGrey)])
        self.control.addTarget(self, action: #selector(self.controlValueChanged), for: .valueChanged)
        self.control.layer.borderColor = Palette.slateGrey.cgColor
        self.control.layer.borderWidth = 1
        view.addSubview(self.control)
        self.control.setNeedsLayout()
    }
    
    @objc func controlValueChanged () {
        guard let control = control else {
            return
        }
        switch control.index {
        default:
            break
        }
    }
    
}
