//
//  RepoProtocols.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol RepoViewProtocol: class {
    var presenter: RepoPresenterProtocol?  { get set }
    var repoTableView: UITableView!  { get set }
}
//MARK: Presenter -
protocol RepoPresenterProtocol: class {
    var view: RepoViewProtocol?  { get set }
    func loadRepos()
}

//MARK: Interactor -
protocol RepoInteractorOutputProtocol: class {

  
}
protocol RepoInteractorInputProtocol: class {

  var presenter: RepoInteractorOutputProtocol?  { get set }
}

//MARK: Router -
protocol RepoRouterProtocol: class {
    var view: UIViewController! { get set }
    
}
