//
//  RepoPresenter.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RepoPresenter: BasePresenter,RepoPresenterProtocol {

    weak internal var view: RepoViewProtocol?
    var interactor: RepoInteractorInputProtocol?
    private let router: RepoRouterProtocol
    private var dataSource:RepoCellDataSource?
    
    init(view: RepoViewProtocol, interactor: RepoInteractorInputProtocol?, router: RepoRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    func loadRepos() {
        guard let view =  self.view else {
            return
        }
        dataSource = RepoCellDataSource(delegate: self, tableView: view.repoTableView)
    }

}

extension RepoPresenter:RepoCellDataSourceDelegate{
    func didSelected() {
        
    }
    
}

extension RepoPresenter: RepoInteractorOutputProtocol {
    
}
