//
//  HomeRouter.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeRouter: HomeRouterProtocol {
    var view: UIViewController!
    
    func loadRepo() {
        if let main = view as? HomeViewController {
            let vc : RepoViewController = UIViewController.instanceXib()
            RepoConfig().createModule(view: vc)
            
            main.replaceChild(viewController: vc)
        }
    }
    
    func loadFav() {
        if let main = view as? HomeViewController {
            let vc : FavouriteViewController = UIViewController.instanceXib()
            FavouriteConfig().createModule(view: vc)
            
            main.replaceChild(viewController: vc)
        }
    }
    
    func navigateToSearch() {
        let vc : SearchViewController = UIViewController.instanceXib()
        SearchConfig().createModule(view: vc )
        view.show(vc, sender: view)
    }
    
}
