//
//  HomeProtocols.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol HomeViewProtocol: class {
    var presenter: HomePresenterProtocol?  { get set }
    var container: UIView! { get set }
    func replaceChild(viewController: UIViewController )
}
//MARK: Presenter -
protocol HomePresenterProtocol: class {
    var view: HomeViewProtocol?  { get set }
    var childViewController: UIViewController! { get set }
    func loadRepo()
    func loadFav()
}

//MARK: Interactor -
protocol HomeInteractorOutputProtocol: class {

  
}
protocol HomeInteractorInputProtocol: class {

  var presenter: HomeInteractorOutputProtocol?  { get set }
}

//MARK: Router -
protocol HomeRouterProtocol: class {
    var view: UIViewController! { get set }
    
}
