//
//  HomeViewController.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewController: BaseViewController, HomeViewProtocol {
    
    @IBOutlet weak var container: UIView!
    @IBOutlet weak var tabBar: UITabBar!
    
    var presenter: HomePresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        tabBar.delegate = self
        setLayout()
        listToNetworkChange()
        HomeConfig().createModule(view: self)
        self.presenter?.loadRepo()
        tabBar.selectedItem = tabBar.items?.first
    }
    
    func setLayout() {
        navigationController!.navigationBar.prefersLargeTitles = true
        self.title = "Repositories"
        setNavigation()
        navigationController!.navigationBar.largeTitleTextAttributes = [NSAttributedString.Key.foregroundColor: Palette.dark]
        self.view.backgroundColor = Palette.bg
        self.tabBar.barTintColor = Palette.bg
        self.tabBar.layer.borderColor = UIColor.clear.cgColor
        tabBar.layer.borderWidth = 0.50
        self.tabBar.clipsToBounds = true
    }
    
    func replaceChild(viewController: UIViewController ) {
        
        if let view = self.container.subviews.last {
            view.removeFromSuperview()
        }
        
        self.addChild(viewController)
        
        self.container.addSubview(viewController.view)
        self.container.bringSubviewToFront(viewController.view)
        viewController.view.frame = CGRect(x: 0, y: 0, width: self.container.frame.width, height: self.container.frame.height)
        
        self.presenter?.childViewController = viewController
        
    }
    @IBAction func search(_ sender: Any) {
        self.presenter?.navigateToSearch()
    }
    
}

extension HomeViewController:UITabBarDelegate{
    func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        if(item.tag == 1) {
           //repo
            self.presenter?.loadRepo()
        }
        else if(item.tag == 2) {
           // fav
            self.presenter?.loadFav()
        }
    }
}
