//
//  HomePresenter.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter: BasePresenter,HomePresenterProtocol {
    
    
    var childViewController: UIViewController!
    
    weak internal var view: HomeViewProtocol?
    weak var interactor: HomeInteractorInputProtocol?
    
    private let router: HomeRouterProtocol
    
    init(view: HomeViewProtocol, interactor: HomeInteractorInputProtocol?, router: HomeRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    func loadRepo() {
        self.router.loadRepo()
    }
    
    func loadFav() {
        self.router.loadFav()
    }
    func navigateToSearch() {
        self.router.navigateToSearch()
    }
    
}

extension HomePresenter: HomeInteractorOutputProtocol {
    
}
