//
//  SearchInteractor.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/16/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchInteractor: BaseInteractor<AppTarget>,SearchInteractorInputProtocol {
    
    weak var presenter: SearchInteractorOutputProtocol?
    
    func searchRepos(str: String,page:Int) {
        request(targetType: .fetchRepos(query: str, page: page)) { [weak self] (response: FetchReposResponse) in
            guard let strongSelf = self else { return }
            guard let repos = response.items else { return }
            strongSelf.presenter?.didload(repos: repos)
            
        }
    }
    func toggleToFavourite(repo: Repos) {
        guard let id = repo.id else {
            return
        }
        if CacheHandler.ids.contains(id) {
            let _ = CacheHandler.shared.deleteObject(object: repo)
            
        } else {
            let _ = CacheHandler.shared.SaveData(object: repo)
            
        }
    }
    
}
