//
//  SearchRouter.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/16/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchRouter: SearchRouterProtocol {
    
    var view: UIViewController!
    func showDetails(with repo: Repos) {
        let vc:DetailsViewController = UIViewController.instanceXib()
        DetailsConfig().createModule(view: vc, repo: repo)
        view.show(vc, sender: view)
    }
    
}
