//
//  SearchConfig.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/16/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchConfig: BaseConfig{
    func createModule(view: SearchViewController) {
        
        let interactor: SearchInteractor = SearchInteractor()
        let router: SearchRouter = SearchRouter()
        
        let presenter: SearchPresenter = SearchPresenter(view: view, interactor: interactor, router: router)
        
        router.view = view
        interactor.basePresenter = handleBasePresenter(baseView: view)
        view.presenter = presenter
        interactor.presenter = presenter
        presenter.baseView = view
    }
}
