//
//  SearchProtocols.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/16/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol SearchViewProtocol: class {
    var presenter: SearchPresenterProtocol?  { get set }
    var searchTable: UITableView! { get set }
}
//MARK: Presenter -
protocol SearchPresenterProtocol: class {
    var view: SearchViewProtocol?  { get set }
    func searchRepos(str:String)
    func clearTable()
}

//MARK: Interactor -
protocol SearchInteractorOutputProtocol: class {
    func didload(repos:[Repos])
}
protocol SearchInteractorInputProtocol: class {
    
    var presenter: SearchInteractorOutputProtocol?  { get set }
    func searchRepos(str: String,page:Int)
    func toggleToFavourite(repo: Repos)
}

//MARK: Router -
protocol SearchRouterProtocol: class {
    var view: UIViewController! { get set }
    func showDetails(with repo: Repos)
}
