//
//  SearchViewController.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/16/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchViewController: BaseViewController, SearchViewProtocol {

    @IBOutlet weak var searchBar: UISearchBar!
    @IBOutlet weak var searchTable: UITableView!
    
    var presenter: SearchPresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        searchBar.delegate = self
    }

}


extension SearchViewController:UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        if searchText.isEmpty  {
            presenter?.clearTable()
        } else {
            presenter?.searchRepos(str: searchText)
        }
    }
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        if let str  = searchBar.text ,!str.isEmpty{
            presenter?.searchRepos(str: str)
        }
    }
}
