//
//  FavouriteInteractor.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteInteractor: BaseInteractor<AppTarget>,FavouriteInteractorInputProtocol {
    
    weak var presenter: FavouriteInteractorOutputProtocol?
    
    func loadUserFavItems() {
        let repos = CacheHandler.shared.loadAllCachedData()
        presenter?.didLoadFavItems(items: repos)
    }
    
    
}
