//
//  FavouriteProtocols.swift
//  GithubVIPER
//
//  Created Mena Gamal on 8/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol FavouriteViewProtocol: class {
    var presenter: FavouritePresenterProtocol?  { get set }
    var favTable: UITableView!  { get set }
}
//MARK: Presenter -
protocol FavouritePresenterProtocol: class {
    var view: FavouriteViewProtocol?  { get set }
    func loadAllFavItems()  
}

//MARK: Interactor -
protocol FavouriteInteractorOutputProtocol: class {
    func didLoadFavItems(items:[Repos]) 
}
protocol FavouriteInteractorInputProtocol: class {

  var presenter: FavouriteInteractorOutputProtocol?  { get set }
    func loadUserFavItems()
}

//MARK: Router -
protocol FavouriteRouterProtocol: class {
    var view: UIViewController! { get set }
    func showDetails(with repo: Repos)
}
